// Generated by CoffeeScript 1.6.3
(function() {
  var app;

  app = angular.module('CoffeeModule');

  app.controller("FieldMarshalCtrl", function($scope, $store, $http, FieldMarshal) {
    var mungeSlavesToProcs;
    $store.bind($scope, "fieldmarshalInfo");
    $http.defaults.headers.common.authorization = "Basic " + (btoa("quartermaster:" + $scope.fieldmarshalInfo.pass));
    mungeSlavesToProcs = function(slaves) {
      var name, pid, proc, slave, _results;
      $scope.allProcs = [];
      _results = [];
      for (name in slaves) {
        slave = slaves[name];
        _results.push((function() {
          var _ref, _results1;
          _ref = slave.processes;
          _results1 = [];
          for (pid in _ref) {
            proc = _ref[pid];
            proc.slave = name;
            proc.port = proc.opts.env.PORT;
            _results1.push($scope.allProcs.push(proc));
          }
          return _results1;
        })());
      }
      return _results;
    };
    $scope.getSlaves = function() {
      return FieldMarshal.get({
        action: 'slaves',
        host: "" + $scope.fieldmarshalInfo.host + ":" + $scope.fieldmarshalInfo.port
      }, function(data, status, headers, config) {
        mungeSlavesToProcs(data);
        $scope.slavesStr = JSON.stringify(data, null, "  ");
        return $scope.slaves = data;
      });
    };
    setInterval($scope.getSlaves, 3000);
    $scope.getSlaves();
    $scope.sort = {
      column: 'port',
      descending: 'true'
    };
    $scope.changeSorting = function(column) {
      var sort;
      sort = $scope.sort;
      if (sort.column === column) {
        return sort.descending = !sort.descending;
      } else {
        sort.column = column;
        return sort.descending = false;
      }
    };
    return $scope.stop = function(slave, pid) {
      return FieldMarshal.save({
        action: 'stop',
        host: "" + $scope.fieldmarshalInfo.host + ":" + $scope.fieldmarshalInfo.port,
        slave: slave,
        ids: [pid]
      });
    };
  });

}).call(this);
