// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('fieldMarshalService', ['ngResource']).factory('FieldMarshal', function($resource) {
    return $resource('http://:host/:action', {
      action: '@action',
      host: '@host'
    });
  });

}).call(this);
